### ISSUE TITLE
Not working with Playdate OS 2 and macOS 12.6.7

### ISSUE THREAD

**Issue by hteumeuleu** [cranksters/pd-usb#2]
Hey there,

Thanks for all your amazing work on the Playdate. I've been trying this project it in Chrome or Edge on macOS 12.6.7 with a Playdate on OS 2, but the browser window always tells me that no device is available. Going to `chrome://device-log/` on the browser shows me the device is connected (with `vendor=4913 "Panic Inc", product=22337`). I'm under the impression the product ID has changed since the library was written. (The `PLAYDATE_PID = 0x5740` in your code equals 22336). I've tried forking the project to change this id in the compiled version used by the samples (https://hteumeuleu.github.io/pd-usb/) but still no success. 

Does this still work on your end?

**Comment by gingerbeardman** [comment]
I guess your device is different hardware than the one used to develop this.

Should be relatively easy to add in the extra product ID.

https://github.com/jaames/pd-usb/blob/f202763732924803a0be371df1b86fdbc648deec/src/PlaydateDevice.ts#L22-L24

**Comment by jaames** [comment]
I honestly haven't touched my Playdate since 2.0 came out so I haven't verified if anything changed on their end yet. It would be weird for an OS release to change a product ID. Is this a brand new device you just received or did it connect properly before 2.0?

**Comment by hteumeuleu** [comment]
My Playdate was part of the Group 1 shipping. I haven't tested it before so I don't know if the product ID was different before 2.0.

**Comment by hteumeuleu** [comment]
I just rechecked in Chrome (_Version 118.0.5957.0 (Build officiel) canary (x86_64)_) and the weird thing is I get two devices for the Playdate under `chrome://device-log/`.

<img width="990" alt="Screenshot of Chrome device-log page showing two Playdate devices detected via USB. One with the productID=22336 and the other with productID=22337." src="https://github.com/jaames/pd-usb/assets/3451753/06466fbd-c0fb-422b-8c54-d998b2bff42b">

Still, I get no luck when trying your web examples and got no compatible devices detected.

<img width="990" alt="A screenshot of the first example from this repo in Chrome showing no device detected." src="https://github.com/jaames/pd-usb/assets/3451753/2ab43848-09ab-4f0f-90ed-e69a5d969296">

Is there something specific to do in Chrome to get the Playdate detected? I'm using a non-official USB-C to USB-C cable, could it come from there? (The Playdate is still mounted correctly under macOS finder.)

**Comment by hteumeuleu** [comment]
Oh wait, I just realized my mistake. The Playdate must not be in Data Disk Mode for this to work. Just having the Playdate plugged in is enough to get this to work. (And it works great!) Sorry for wasting your time. And thanks for this library!
